DELETE FROM `_oud_graadmeter`;
INSERT INTO `_oud_graadmeter` (`positie`,`positie_vw`,`aantal_wk`,`artiest`,`track`,`ijsbreker`,`ex_ijsbreker`)
 VALUES(-1,-6,7,'Jacco Gardner','Clear The Air','N','N')
,(-2,-2,9,'San Cisco','Wild Things','N','N')
,(-3,-8,3,'We Show Up On Radar','The Anchors Of My Heart','N','N')
,(-4,-3,6,'Ty Segall','Thank God for Sinners','N','N')
,(-5,-9,4,'Jake Bugg','Taste It','N','N')
,(-6,-4,4,'Vacationer','Tip','N','N')
,(-7,-1,5,'Foxygen','San Francisco','N','N')
,(-8,-5,4,'Dexters','Recover','N','J')
,(-9,-7,5,'Courteneers','Lose Control','N','N')
,(-10,-19,3,'Jimi Hendrix','Somewhere','N','N')
,(-11,-10,3,'The Men','Electric','N','J')
,(-12,-20,2,'Sivu','Better Man Than He','N','J')
,(-13,0,1,'Diiv','Wait','J','N')
,(-14,-13,6,'Woods','Size Meets The Sound','N','N')
,(-15,0,1,'Guards','Ready To Go','N','N')
,(-16,-15,3,'Tame Impala','Mind Mischief','N','N')
,(-17,0,1,'Matthew E. White','Big Love','N','N')
,(-18,-18,4,'Jackie Onassis','Crystal Balling','N','N')
,(-19,-12,5,'Local Natives','Heavy Feet','N','J')
,(-20,0,1,'Youth Lagoon','Dropla','N','N')
,(-21,-16,8,'Josef Salvat','This Life','N','N')
,(-22,0,1,'Woodkid','I Love You','N','N')
,(-23,-22,4,'Sinkane','Runnin''','N','N')
,(-24,0,1,'Half Moon Run','Call Me In The Afternoon','N','N')
,(-25,-24,2,'Veronica Falls','Do It Yourself','N','N')
,(-26,-26,3,'Dutch Uncles','Flexxin''','N','N')
,(-27,-17,5,'Foals','My NUmber','N','N')
,(-28,0,1,'Veils','Through The Deep Dark Woods','N','N')
,(-29,-28,2,'Moon Duo','Ich Werde Sehen','N','N')
,(-30,0,1,'Pignose Willy''s','Shake ''em On Down','N','N');

DELETE FROM `_oud_graadmeter_tip10`;
INSERT INTO `_oud_graadmeter_tip10` (`positie`,`positie_vw`,`aantal_wk`,`artiest`,`track`,`ijsbreker`,`ex_ijsbreker`)
 VALUES(1,0,0,'Stuart Warwick','Crush','N','N')
,(2,0,0,'Phoenix','Entertainment','N','N')
,(3,0,0,'Strokes','All The Time','N','N')
,(4,0,0,'Phosphorescent','Song For Zula','N','N')
,(5,0,0,'Young Dreams','First Days Of Something','N','N')
,(6,0,0,'Mowgli''s','San Francisco','N','N')
,(7,0,0,'Watsky ft. Kate Nash','Hey, Asshole','N','N')
,(8,0,0,'Villagers','The Bell','N','N')
,(9,0,0,'Kids These Days','Doo Wah','N','N')
,(10,0,0,'Dive Bella Dive','School','N','N');

DELETE FROM `_oud_graadmeter_exit`;
INSERT INTO `_oud_graadmeter_exit` (`positie`,`positie_vw`,`aantal_wk`,`artiest`,`track`,`ijsbreker`,`ex_ijsbreker`)
 VALUES(1,-30,1,'K-X-P','Look At The Light','N','N')
,(2,-29,4,'TDTMCM','Helikopter','N','N')
,(3,-27,7,'Mister and Mississippi','Nothern Sky','N','N')
,(4,-25,7,'Hooray For Earth','Never','N','J')
,(5,-23,4,'Frightened Rabbit','The Woodpile','N','J')
,(6,-21,7,'Kensington','Home Again','N','N')
,(7,-14,6,'Cold War Kids','Miracle Mile','N','J')
,(8,-11,3,'Deep Vally','Lies','N','N');
